### ISSUE TITLE
Using Sass

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf-mkdoc-theme#10]
@weierophinney 
Do you see a chance to compile Sass?

Add the moment there are too many CSS files and the internal structure is far away from good.

**Comment by weierophinney** [comment]
@froschdesign As long as you're talking about doing so in conjunction with bootstrap, we could investigate it. I'd definitely like to slim down the amount of CSS / JS required on each request; I've just been more focused on getting something usable.

The big issue with doing so right now, however, is that I started from an existing mkdocs theme, which included only the compiled bootstrap CSS/JS and the theme layer. Adding the SASS sources back in may be a bit problematic. If you want to give it a try, be my guess; I'll definitely review a PR. :smile:

**Comment by froschdesign** [comment]
> As long as you're talking about doing so in conjunction with bootstrap, we could investigate it.

Yes!

>  If you want to give it a try…

I will test it.

**Comment by webimpress** [comment]
@froschdesign are you working on it or can I prepare something? :)

**Comment by froschdesign** [comment]
@webimpress 
We need the automatic compilation of Sass. Maybe with help by Travis?!

**Comment by webimpress** [comment]
@froschdesign please have a look on #21

**Comment by froschdesign** [comment]
Fixed with #21
