### ISSUE TITLE
Missing a useful footer

### ISSUE THREAD

**Issue by xtreamwayz** [zendframework/zf-mkdoc-theme#12]
I'm missing some navigation on the current docs on github.io. 

- There is no way to go back to the main page (zendframework.github.io). Not that this is really needed since there is a component list anyway, but it doesn't feel natural. If you entered via the mainpage you'd like to go back there.

- There are no links to the tutorials yet (I know it has been added only since last night). It doesn't make sense to add these to the components list.

What I'm thinking about is a footer like the one in the new [official website](https://github.com/ezimuel/zf3-web/blob/master/templates/include/footer.phtml). It could feature some external links, links to the most important packages like installers, tutorials and getting started pages and probably links to the ZF1 and ZF2 docs.

**Comment by froschdesign** [comment]
@xtreamwayz 
The documentation, the documentation template and also the website are still under construction.
Please have a little patience.

**Comment by xtreamwayz** [comment]
I know people are spending a lot of time these days to create the documentation for ZF3 and the new website. 

I'm just mentioning it here so it can be improved some day. I have no idea where to go to with my idea otherwise. Well, IRC would be an option but they are still sleeping in the US.

I can even create a PR and add it, but I think there are people more qualified to decide what should be in such footer.

**Comment by froschdesign** [comment]
Don't get me wrong. Ideas are always welcome and the issue tracker is good place for this.

> …they are still sleeping in the US.

The community and the ZF members come from around the world. Not only from US. :wink:

**Comment by weierophinney** [comment]
When we're ready to go live with the website relaunch, we'll also be updating the theme to match, including the footer. Thanks for creating the issue, though, so we have a public item to track with!

**Comment by weierophinney** [comment]
Fixed with the 0.5.0 release. :smile:
