### ISSUE TITLE
Broken layout on 404 pages

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf-mkdoc-theme#24]
If a 404 page is loaded, then a different CSS file is used. On a 404 page all URLs are absolute and so the CSS and JS files are used from docs.zendframework.com, which doesn't include all styles or has different styles.

Original issue: zendframework/tutorials#64

(Btw. why is the font family different between the homepage of the docs and all components?)

**Comment by weierophinney** [comment]
> why is the font family different between the homepage of the docs and all components

Likely because we developed them separately. :smile:

Any chance you can provide a PR for this issue (the CSS/JS links)?

**Comment by froschdesign** [comment]
> Any chance you can provide a PR for this issue (the CSS/JS links)?

The problem I see: `mkdocs` creates always absolute URLs for the 404 error page. ([`mkdocs/build.py`](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/commands/build.py#L301))
And there is another problem in the navigation top-bar and at the home link, because all these links points to docs.zendframework.com. For example:

- docs.zendframework.com/intro
- docs.zendframework.com/quick-start
- …

[This fix on `mkdocs`](https://github.com/mkdocs/mkdocs/pull/1039) should solved the problem, but at the ZF docs it doesn't work?!

**Comment by froschdesign** [comment]
A new 404 page is included in my PR: #34

**Comment by froschdesign** [comment]
The problem is fixed.

Example: https://docs.zendframework.com/zend-form/element/monthselect/
