### ISSUE TITLE
zf-component-list.json - missing packages

### ISSUE THREAD

**Issue by webimpress** [zendframework/zf-mkdoc-theme#32]
Any idea how `zf-component-list.json` on `gh-pages` branch is generated?

There are some missing modules (like `zend-expressive-hal`) and maybe more ....

**Comment by webimpress** [comment]
Oh... never mind... It's there:
https://github.com/zendframework/zf-mkdoc-theme/blob/gh-pages/scripts/zf-component-list.json#L117-L121

**Comment by froschdesign** [comment]
@webimpress 
> Any idea how zf-component-list.json on gh-pages branch is generated?

I think, by a local script from @weierophinney. (I don't know any other location or repository.)

> Oh... never mind... It's there:

Not in the documentation overview: https://docs.zendframework.com !

**Comment by webimpress** [comment]
@froschdesign
> Not in the documentation overview: https://docs.zendframework.com !

Oh, you have right, I was looking there, and then in component list from some documentation page... Reopening then!

**Comment by webimpress** [comment]
Resolved in https://github.com/zendframework/zendframework.github.io/pull/4
