### ISSUE TITLE
cross component linking

### ISSUE THREAD

**Issue by basz** [zendframework/zf-mkdoc-theme#4]
not sure how to do it, but could we investigate cross component linking. So one can easily jump from for example zend-servicemanager to zend-config via the menu?

Edit : By the way, nice work on the theming and tool chain

**Comment by weierophinney** [comment]
We're working on a solution for this, but don't have an ETA at this time.
The plan is a div above the header that we can toggle to display links to
all components.

**Comment by froschdesign** [comment]
Work in progress: #9
