### ISSUE TITLE
Rearrange components list into categories

### ISSUE THREAD

**Issue by CaduEspindola** [zendframework/zf-mkdoc-theme#42]
# Components  List
## Problem
All components are displayed togheter in the same grouping called "Components" (zend-expressive components, zend-mvc components, application-skeletons and class components). There is no specific categorization for each of them - the same problem on the main page (see the screeenshots at the end).

## Suggestion
The documentation could be rearranged into categories:
1. **Application Providers** or **Application Skeletons** (any better name?): zend-mvc-skeleton and zend-expressive;
2. **Expressive Components**: all zend-expressive-* packages (and middlewares);
3. **MVC Components**: all zend-mvc-* packages;
4. **Class Components**: all others class packages.

## Screeenshots
![components](https://user-images.githubusercontent.com/35963929/40735071-9757155c-6410-11e8-9220-3ae88e210b6e.png)

**Comment by froschdesign** [comment]
We need a complete list of all categories / groups and their associated components.

Help and suggestions are always welcome! 😃

**Comment by CaduEspindola** [comment]
My Suggestion:

**Application Providers** or **Application Skeletons** (any better name?)
- zend-expressive
- zend-mvc (currently [https://docs.zendframework.com/tutorials/getting-started/skeleton-application/](https://docs.zendframework.com/tutorials/getting-started/skeleton-application/))

**Expressive Components**
- zend-expressive-authentication
- zend-expressive-authentication-basic
- zend-expressive-authentication-session
- zend-expressive-authentication-zendauthentication
- zend-expressive-csrf
- zend-expressive-flash
- zend-expressive-hal
- zend-expressive-session
- zend-expressive-session-ext

**MVC Components**
- zend-modulemanager
- zend-mvc
- zend-mvc-console
- zend-mvc-i18n
- zend-mvc-plugin-fileprg
- zend-mvc-plugin-flashmessenger
- zend-mvc-plugin-identity
- zend-mvc-plugin-prg

**Class Components**
- zend-authentication
- zend-barcode
- zend-cache
- zend-captcha
- zend-code
- zend-component-installer
- zend-config
- zend-config-aggregator
- zend-config-aggregator-modulemanager (maybe zend-mvc?)
- zend-config-aggregator-parameters
- zend-console
- zend-crypt
- zend-db
- zend-debug
- zend-di
- zend-diactoros
- zend-dom
- zend-escaper
- zend-eventmanager
- zend-feed
- zend-file
- zend-filter
- zend-form
- zend-http
- zend-httphandlerrunner
- zend-hydrator
- zend-inputfilter
- zend-i18n
- zend-json
- zend-json-server
- zend-ldap
- zend-loader
- zend-log
- zend-mail
- zend-math
- zend-memory
- zend-mime
- zend-navigation
- zend-paginator
- zend-permissions-acl
- zend-permissions-rbac
- zend-problem-details
- zend-progressbar
- zend-psr7bridge
- zend-router
- zend-serializer
- zend-server
- zend-servicemanager
- zend-servicemanager-di
- zend-session
- zend-soap
- zend-stdlib
- zend-stratigility
- zend-tag
- zend-test
- zend-text
- zend-uri
- zend-validator
- zend-view
- zend-xmlrpc
- zend-xml2json

**Comment by froschdesign** [comment]
Fixed with version [0.6.2](https://github.com/zendframework/zf-mkdoc-theme/releases/tag/0.6.2)

@CaduEspindola 
Thank you for that suggestion!
