### ISSUE TITLE
Allow typing in the component select

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf-mkdoc-theme#43]
[Original feature request]( https://github.com/zendframework/zf-mkdoc-theme/pull/34#issuecomment-389575846) from @weierophinney in #34:

> Allow typing in the component select (fuzzy match, basically)

**Comment by froschdesign** [comment]
A solution can be [Choices.js](https://joshuajohnson.co.uk/Choices/). See the example under "Single select input" with "Option groups".

**Comment by weierophinney** [comment]
I've been working on this all day, and am really struggling.

I have a working prototype here:

- https://gist.github.com/weierophinney/d6d74ae1314018c7042505ce78b80000

If you save that locally and pull it up in a browser, it does exactly what it needs to: pulls the component list, and then populates the dropdown, complete with option groups and ability to jump to a new documentation section.

However, no matter how I try to add this to the theme, it will not work.

I've tried using static assets as I did in the gist. The only way it would work is if I removed all other scripts from the page (though I think the culprits were specifically jquery and/or bootstrap). Even then, it would only work if I changed how the `Choices` instance is populated: I had to eliminate option groups, and push in choices at instantiation, which was doubly odd as passing them at instantiation never worked in the prototype.

I've tried adding the Choices.js module via node, and compiling the assets in the gulp tasks. When I do that, I get both unstyled content, as well as no population of the dropdown.

I've tried dropping `console.log` statements in, to verify it's being triggered. It is, and I get expected values at every turn.

The only thing I can think of at this point is that bootstrap and/or jquery are conflicting. They shouldn't be (the component is written in vanilla JS, with a few ES5 bits thrown in).

If anybody wants to give it a go and help me out, I'd appreciate it.

**Comment by froschdesign** [comment]
@weierophinney 
My changes:

`asset/package.json`:

```json
  "devDependencies": {
    "anchor-js": "^3.2.1",
    "bootstrap-sass": "^3.3.7",
    "choices.js": "^3.0.4",
    "…": "…",
  }
```

`asset/gulpfile.js`:

```js
gulp.task('scripts', function () {
    var prismComponents = [];
    for (var component in prism) {
        prismComponents[component] = 'node_modules/prismjs/components/prism-' + prism[component] + '.js';
    }

    return gulp.src(
        prismComponents.concat(
            [
                'node_modules/prismjs/plugins/normalize-whitespace/prism-normalize-whitespace.min.js',
                'node_modules/prismjs/plugins/line-numbers/prism-line-numbers.min.js',
                'node_modules/jquery/dist/jquery.min.js',
                'node_modules/bootstrap-sass/assets/javascripts/bootstrap.min.js',
                'node_modules/anchor-js/anchor.min.js',
                'node_modules/choices.js/assets/scripts/dist/choices.js', // <-- New
                'js/component-list.js',
                '…'
```

`asset/sass/styles.scss`:

```css
@import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700');
@import 'settings';
@import '../node_modules/bootstrap-sass/assets/stylesheets/bootstrap-sprockets';
@import '../node_modules/bootstrap-sass/assets/stylesheets/bootstrap';
@import '../node_modules/font-awesome/scss/font-awesome';
@import '../node_modules/choices.js/assets/styles/scss/choices'; // <-- New
@import '…';
```

And I updated the file `asset/js/component-list.js` with your code from the Gist.

I tried only one select list:

```js
var choices = new Choices(document.getElementsByClassName('component-selector__control')[1], {…});
```

A little bit small, but it works.

**Comment by weierophinney** [comment]
Thanks, @froschdesign ! I think it may have been how I was importing the CSS then; I'd tried a `<link>` tag as well as adding the dist CSS (not minimized) to the gulpfile, but not importing the SASS file into our own styles. Once I did that, I was able to get it to work finally.

#45 is the final product.
