### ISSUE TITLE
Automated Deploy of Travis-CI mkdocs build question

### ISSUE THREAD

**Issue by brianjking** [zendframework/zf-mkdoc-theme#5]
Hello,

I came across your excellent blog post via the issue I opened at the MkDocs repo (see: https://github.com/mkdocs/mkdocs/issues/840) and they sent me to your blog at https://mwop.net/blog/2016-01-29-automating-gh-pages.html. First off, thank you for writing this and excellent job.

I'm confused about how to avoid overwriting a `CNAME` file for Github pages with this approach though. I thought it was the `-clean` command so I've removed it (see: https://github.com/brianjking/hudsonvalleyhelp/blob/master/.travis.yml#L15), however, it keeps getting deleted.

Any guidance? Thanks!

**Comment by weierophinney** [comment]
@brianjking In your deployment setup, I'd:

- move the CNAME file out of the directory prior to generating docs.
- move it back in when done, but *prior* to adding files to commit.

We don't have that baked into this repo at this time, as we're not deploying any under CNAMEs currently.
