### ISSUE TITLE
Remove word break from code elements in tables

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf-mkdoc-theme#51]
There are some ugly word breaks in code elements that are included in tables.

Examples:

* https://docs.zendframework.com/zend-authentication/adapter/http/#configuration-options
* https://docs.zendframework.com/zend-form/helper/abstract-helper/#public-methods
* https://docs.zendframework.com/zend-navigation/helpers/intro/

**Comment by thexpand** [comment]
We could add
```
table {
    code {
        word-break: keep-all;
    }
}
```

**Comment by froschdesign** [comment]
The problem is `break-word`. See: https://caniuse.com/#search=word-break
I already have a fix for this.
