### ISSUE TITLE
Switching to version 1.0 of MkDocs

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf-mkdoc-theme#52]
https://github.com/mkdocs/mkdocs/pull/1574
https://github.com/mkdocs/mkdocs/releases/tag/1.0
https://www.mkdocs.org/about/release-notes/#version-10-2018-08-03

**Comment by weierophinney** [comment]
Will this take much effort to accomplish? I.e., are there many breaking changes with 1.0, or does upgrading to it mostly "just work"?
