### ISSUE TITLE
gulp-sass cannot be installed

### ISSUE THREAD

**Issue by xtreamwayz** [zendframework/zf-mkdoc-theme#61]
Using node 10, the gulp-sass package cannot be installed via npm. The solution is to update to version `^4.0.0`.

https://github.com/zendframework/zf-mkdoc-theme/blob/d3ed0d65c50e7fb8ebe60d0aa525ae37846d1e0b/asset/package.json#L27

**Comment by froschdesign** [comment]
Will be updated with #52

**Comment by froschdesign** [comment]
Fixed with 5f7be16ac9e17e82cb932e8cda05e241d0379b6d
