### ISSUE TITLE
Improve the page title of the HTML document

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf-mkdoc-theme#67]
At the moment we have:

> Home - zend-expressive-session-cache

The "Home" is useless here and should not be output. The same was done for the breadcrumbs and sub-navigation.

https://docs.zendframework.com/zend-expressive-session-cache/

**Comment by xtreamwayz** [comment]
I agree, it takes you away from the docs which is not most users want.

**Comment by froschdesign** [comment]
New suggestion:

> zend-expressive-session-cache - Zend Framework Docs
