### ISSUE TITLE
Render all component documentations again

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf-mkdoc-theme#77]
We must render all component documentations again to resolve different problems:

* the component selector is missing in many documentations
* to include all new updates and bugfixes
* _…_

**Comment by froschdesign** [comment]
@weierophinney 
I think we should test the rendering on one component and after we checked all links and elements, then we can run it for all comeponents.

**Comment by weierophinney** [comment]
I built the tutorials docs first, and went through and checked all functionality - which was key, as I'd forgotten to push the change that had re-built the assets, so the anchor.js functionality was not working! After pushing that change and triggering another build, those docs look perfect, so I'm triggering builds of all of them. Should be done in the next 30 minutes or so.
