### ISSUE TITLE
Update to version 3.4 of Bootstrap (for Sass)

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf-mkdoc-theme#78]
* https://blog.getbootstrap.com/2018/12/13/bootstrap-3-4-0/
* https://www.npmjs.com/package/bootstrap-sass

**Comment by froschdesign** [comment]
https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/

**Comment by webimpress** [comment]
@froschdesign it should be closed as well (commit: 5f7be16)
